apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: baas-db
  namespace: baas
spec:
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 18
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
    roles:
      - name: app
        login: true
        superuser: true
      - name: anon
        ensure: present
        comment: PostgREST Anonymous Role
      - name: authenticated
        ensure: present
        comment: PostgREST Logged-in User Role
      - name: app_admin
        ensure: present
        comment: PostgREST App Admin Role
        bypassrls: true
      - name: authenticator
        ensure: present
        comment: PostgREST Authenticator
        inRoles:
          - anon
          - authenticated
          - app_admin
  instances: 1
  storage:
    size: 2Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: baas-db
  namespace: baas
spec:
  name: app
  cluster:
    name: baas-db
  schemas:
    - name: api
      owner: app
    - name: auth
      owner: app
    - name: dbo
      owner: app
    - name: storage
      owner: app
  extensions:
    - name: uuid-ossp
    - name: pgcrypto
    - name: citext
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: baas-db-ingress
  namespace: baas
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`db.baas.wke.csie.ncnu.edu.tw`)
      services:
        - name: baas-db-rw
          port: 5432
  tls:
    secretName: baas-wildcard-tls
