apiVersion: v1
kind: ConfigMap
metadata:
  name: baas-auth-config
  namespace: baas
data:
  EMAIL_AND_PASSWORD_ENABLED: "true"
  JWT_EXPIRATION_TIME: "15m"
  TRUSTED_ORIGINS: "http://localhost:5173"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baas-auth
  namespace: baas
  labels:
    app: baas-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baas-auth
  template:
    metadata:
      labels:
        app: baas-auth
    spec:
      containers:
        - name: auth
          image: ghcr.io/wkebaas/auth:v0.0.2
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: baas-auth-secret
            - configMapRef:
                name: baas-auth-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: baas-db-app
                  key: uri
---
apiVersion: v1
kind: Service
metadata:
  name: baas-auth
  namespace: baas
spec:
  selector:
    app: baas-auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: baas-auth-ingress
  namespace: baas
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`baas.wke.csie.ncnu.edu.tw`) && PathPrefix(`/api/auth`)
      kind: Rule
      services:
        - name: baas-auth
          port: 3000
  tls:
    secretName: wke-tls
