apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: baas-db
  namespace: baas
spec:
  name: app
  cluster:
    name: baas-db
  schemas:
    - name: api
      owner: app
    - name: auth
      owner: app
    - name: dbo
      owner: app
    - name: storage
      owner: app
  extensions:
    - name: uuid-ossp
    - name: pgcrypto
    - name: citext
