apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: baas-db
  namespace: baas
spec:
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
  instances: 1
  storage:
    size: 2Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: baas-db
  namespace: baas
spec:
  name: app
  cluster:
    name: baas-db
  schemas:
    - name: api
      owner: app
    - name: auth
      owner: app
    - name: dbo
      owner: app
    - name: storage
      owner: app
  extensions:
    - name: uuid-ossp
    - name: pgcrypto
    - name: citext
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: baas-db-ingress
  namespace: baas
spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`db.baas.wke.csie.ncnu.edu.tw`)
      services:
        - name: baas-db-rw
          port: 5432
  tls:
    secretName: baas-wildcard-tls
